### ISSUE TITLE
Is it possible to add trusted-public-keys, substituters to the CI config?

### ISSUE THREAD

**Issue by jameshaydon** [garnix-io/issues#2]
So that building can take advantage of public binary caches.

**Comment by jkarni** [comment]
At the moment no, and with the current architecture this is a bit involved. There are also a few questions about trust that need to be thought about. But it would be nice to have some such option.

**Comment by jkarni** [comment]
I think this will stay as a wontfix, since cache poisoning is just too hard to figure out. Sorry!

**Comment by gvolpe** [comment]
I know this is a wontfix, but thought I shared this use case. I have a [Garnix build](https://github.com/gvolpe/nix-config/runs/75974782593) that's timing out after 2 hs.

However, the same job builds on Github Actions because it's able to leverage an [existing binary cache](https://github.com/gvolpe/nix-config/blob/eb153c7dbd692191952254b8180ab99c37741a4b/flake.nix#L15) via [accept-flake-config = true](https://github.com/gvolpe/nix-config/blob/eb153c7dbd692191952254b8180ab99c37741a4b/.github/workflows/home.yml#L68).
