### ISSUE TITLE
Disable building of certain branches

### ISSUE THREAD

**Issue by srid** [garnix-io/issues#37]
Could the YAML file be used to configure this? 

For example, to disable Garnix building `gh-pages` branch: https://github.com/srid/NixHaskellIndex/tree/gh-pages

**Comment by jkarni** [comment]
You could have:

```
builds:
  include: []
```
In the YAML file in the branch. For `gh-pages` that probably works well, since you likely aren't going to be merging in other branches very often; for other things (like certain tests only on master) it doesn't work so well.

**Comment by jkarni** [comment]
I actually don't know how to provide a nice interface to do this aside from the way described above. In theory we could have it be a flag that gets read from `master`/`main`, but that's quite confusing. It could be a global, non-git-based option, but I'd like to avoid this for as long as possible.

I'm closing because of this, but I know it's not a fully satisfactory answer. If anyone has a better idea, please feel free to suggest it and I'll reopen

**Comment by jkarni** [comment]
I'm re-opening this since I realize it's quite useful in selectively disabling things (e.g., only build certain things on master), and in general not workable to have different `garnix.yaml`s per-branch (as you might have in a `gh-pages` branch).
