### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by jkarni** [garnix-io/issues#45]
Provide badges for CI status.

Ideally, provide [an endpoint that is compatible with shields.io](https://shields.io/endpoint). Allow filtering (e.g. `garnix.io/repo/<repo>?format=shields.io&system=x86_64-linux&type=package` for all x86_64-linux packages in the latest commit of `master`/`main`).

Useful query params to have:

- Commit
- Branch
- System
- Type

**Comment by gvolpe** [comment]
Until this is supported, I'm using the following static badge, in case someone wants to borrow it and show support for Garnix.

![badge](https://img.shields.io/static/v1?label=Built%20with&message=Garnix&color=blue&style=flat&logo=nixos&link=https://garnix.io&labelColor=111212)

https://img.shields.io/static/v1?label=Built%20with&message=Garnix&color=blue&style=flat&logo=nixos&link=https://garnix.io&labelColor=111212

**Comment by getchoo** [comment]
another solution may be to use the github statuses api to get the state of the check suite, like so

![](https://img.shields.io/badge/dynamic/json?label=Garnix%20Builds&query=%24.state&url=https%3A%2F%2Fapi.github.com%2Frepos%2Fgetchoo%2Fflake%2Fcommits%2Fmain%2Fstatus&color=blue&style=flat-square&logo=nixos&labelColor=111212)

https://img.shields.io/badge/dynamic/json?label=Garnix%20Builds&query=%24.state&url=https%3A%2F%2Fapi.github.com%2Frepos%2Fgetchoo%2Fflake%2Fcommits%2Fmain%2Fstatus&color=blue&style=flat-square&logo=nixos&labelColor=111212

however, due to issue i've brought up in https://github.com/garnix-io/issues/issues/64, this won't work as expected since statuses seem to always be reported as `pending`, regardless of actual completion

**Comment by sellout** [comment]
This exists, but still needs to be documented before we close this, IMO. Here’s an example:
```md
[![built with garnix](https://img.shields.io/endpoint?url=https%3A%2F%2Fgarnix.io%2Fapi%2Fbadges%2Fsellout%2Fflaky%3Fbranch%3Dmain)](https://garnix.io)
```
[![built with garnix](https://img.shields.io/endpoint?url=https%3A%2F%2Fgarnix.io%2Fapi%2Fbadges%2Fsellout%2Fflaky%3Fbranch%3Dmain)](https://garnix.io)

Just change the user/repo/branch to your own.

**Comment by sellout** [comment]
This is now documented at https://garnix.io/docs/badges, so the issue can be closed.
